version: '3.7'
services:
  verzel-frontend:
    build: ./frontend
    container_name: verzel-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
       - ./frontend/:/dev/app/frontend/
       - ./frontend/node_modules
    working_dir: /dev/app/frontend
    depends_on:
      - verzel-backend

  verzel-backend:
    build: ./backend
    container_name: verzel-backend
    ports:
      - "8000:8000"
    stdin_open: true
    volumes:
       - ./backend:/dev/app/backend/
    working_dir: /dev/app/backend
    depends_on:
      - verzeldb

  verzeldb:
    image: postgres:13.6-alpine
    restart: always
    environment:
      PGDATA: '/data/postgres'
      POSTGRES_USER: ${POSTGRES_USER:-verzel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_DB: ${POSTGRES_PASSWORD:-verzeldb}
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/data/postgres"
volumes:
  dbdata:
